package com.example.app.utils;

public class Constants {

    // todo: base url may change
    public static String BASE_URL = "http://192.168.1.101:8000/api/";

    public static String BUTTON_FILTER = "Filter";
    public static String BUTTON_NO_FILTER = "Remove Filter";

    public static int HOSPITAL_LOOKUP_RADIUS_IN_METERS = 10000;

    // list of all the hospitals included in the demo project
    public static String[] NEARBY_HOSPITAL_NAME_LIST = {
            "Penn Presbyterian Medical Center",
            "Charles Luna Medical Center",
            "Isabella Wells Medical Center",
            "Charles Stewart Medical Center",
            "Joshua Mills Medical Center",
            "Paul Smith Medical Center",
            "Laura Mendez Medical Center",
            "John King Medical Center",
            "Laura Greene Medical Center",
            "Pamela Richards Medical Center",
            "Rebecca Lang Medical Center",
            "Ruben Williams Medical Center",
            "Scott Rowe Medical Center",
            "Jessica Stephens Medical Center",
            "Robert Baker Medical Center",
            "Luis Patterson Medical Center",
            "Mary Perez Medical Center",
            "Richard Adams Medical Center",
            "Anthony Mcdonald Medical Center",
            "Cody White Medical Center",
            "Jeremy Cline Medical Center",
            "Kristina Hughes Medical Center",
            "Sarah Miller Medical Center",
            "Paul Jordan Medical Center",
            "Diane Freeman Medical Center",
            "Jonathan Greene Medical Center",
            "Emily Young Medical Center",
            "James Hubbard Medical Center",
            "Allison Hale Medical Center",
            "Dawn Durham Medical Center",
            "Perry French Medical Center",
            "Christopher Gonzales Medical Center",
            "Scott Smith Medical Center",
            "Michelle Velazquez Medical Center",
            "Luke Foster Medical Center",
            "Kelly Martin Medical Center",
            "Melanie Kelley Medical Center",
            "Dominique Brown Medical Center",
            "Diana Collins Medical Center",
            "Allison White Medical Center",
            "Amy Lee Medical Center",
            "Joseph Evans Medical Center",
            "Brianna Terry Medical Center",
            "David Stephens Medical Center",
            "Aaron Fisher Medical Center",
            "Lynn Price MD Medical Center",
            "Cheyenne Miller Medical Center",
            "Steven Johnson Medical Center",
            "Adam Sanders Medical Center",
            "Sarah Myers Medical Center",
            "Jared Robertson Medical Center",
            "Cory Lopez Medical Center",
            "Christine Nelson Medical Center",
            "David Cooper Medical Center",
            "Nancy Williams Medical Center",
            "Travis Knight Medical Center",
            "Brandon Cook Medical Center",
            "Jessica Wilson Medical Center",
            "Kimberly Clarke Medical Center",
            "Jonathan Watkins Medical Center",
            "Chris Anderson Medical Center",
            "Jason Marshall Medical Center",
            "Pamela Davis Medical Center",
            "Kevin Robinson Medical Center",
            "Meagan Coleman Medical Center",
            "James Anthony Medical Center",
            "Sheryl Gonzalez Medical Center",
            "Rebecca Rosario Medical Center",
            "Dawn Williams Medical Center",
            "Matthew English Medical Center",
            "Lawrence Walker Medical Center",
            "Joshua Blair Medical Center",
            "Alexa Pacheco Medical Center",
            "Leslie Wiggins Medical Center",
            "Kristen Baker Medical Center",
            "Robyn Cole Medical Center",
            "Patrick Hart Medical Center",
            "Anna Smith Medical Center",
            "Ashley Deleon Medical Center",
            "Heather Sanchez Medical Center",
            "Jason Khan Medical Center",
            "Christina Moran Medical Center",
            "Anna Delgado Medical Center",
            "Kerry Holmes Medical Center",
            "Jesse Nguyen Medical Center",
            "Mr. Jason Winters Medical Center",
            "Nancy Wilkinson Medical Center",
            "Russell Torres Medical Center",
            "Michael Baxter Medical Center",
            "Andrew Garrett Medical Center",
            "Theresa Smith Medical Center",
            "Alfred Ramirez Medical Center",
            "Pamela Johnson Medical Center",
            "Matthew Pearson Medical Center",
            "Daniel Gonzalez Medical Center",
            "Heather Reeves Medical Center",
            "Miss Patricia Daniels Medical Center",
            "Regina Gonzalez Medical Center",
            "Kerry Medina Medical Center",
            "Alexander Hunter Medical Center",
            "David Good Medical Center",
    };

}
