# Generated by Django 3.0.4 on 2020-03-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='prodecure_name',
            new_name='procedure_name',
        ),
    ]
